# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    loaders:
        profile:
            filesystem:
                data_root: '%kernel.project_dir%/public%app.path.upload_dir%'
                bundle_resources:
                    enabled: true
    resolvers:
        default:
            web_path:
                web_root: '%kernel.project_dir%/public%app.path.upload_dir%'
                cache_prefix: 'media/cache'
    filter_sets:
        cache: ~
        profile_300x300:
            quality: 90
            filters:
                thumbnail: { size: [300, 300], mode: outbound }
